package me.yunchuang.greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import me.yunchuang.greendao.Note;
import me.yunchuang.greendao.Chat;

import me.yunchuang.greendao.NoteDao;
import me.yunchuang.greendao.ChatDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig noteDaoConfig;
    private final DaoConfig chatDaoConfig;

    private final NoteDao noteDao;
    private final ChatDao chatDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        noteDaoConfig = daoConfigMap.get(NoteDao.class).clone();
        noteDaoConfig.initIdentityScope(type);

        chatDaoConfig = daoConfigMap.get(ChatDao.class).clone();
        chatDaoConfig.initIdentityScope(type);

        noteDao = new NoteDao(noteDaoConfig, this);
        chatDao = new ChatDao(chatDaoConfig, this);

        registerDao(Note.class, noteDao);
        registerDao(Chat.class, chatDao);
    }
    
    public void clear() {
        noteDaoConfig.getIdentityScope().clear();
        chatDaoConfig.getIdentityScope().clear();
    }

    public NoteDao getNoteDao() {
        return noteDao;
    }

    public ChatDao getChatDao() {
        return chatDao;
    }

}
